openapi: "3.0.2"
info:
  title: API Food Truck Tracker
  version: "0.1"
servers:
  - url: https://api.server/v1
paths:
  /trucks:
    get:
      description: Get all trucks in database
      responses:
        "200":
          description: OK
    post:
      description: Create a new truck
      parameters:
      - name: truck
        in: path
        description: Informations to create new food truck
        required: true
        schema:
          type: object
      responses:
        "201":
          description: Created
  /trucks/{id}:
    get:
      description: Get a truck by id
      parameters:
      - name: id
        in: path
        description: ID of the food truck
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
    put:
      description: Update a truck by id
      parameters:
      - name: id
        in: path
        description: ID of the food truck
        required: true
        schema:
          type: integer
          format: int64
      - name: truckInfo
        in: path
        description: Informations that should be updated
        required: true
        schema:
          type: object
      responses:
        "200":
          description: OK
    delete:
      description: Delete a truck by id
      parameters:
      - name: id
        in: path
        description: ID of the food truck
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /users/{id}:
    get:
      description: Get a user by id
      parameters:
      - name: id
        in: path
        description: ID of the user
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
    put:
      description: Update a user by id
      parameters:
      - name: id
        in: path
        description: ID of the user
        required: true
        schema:
          type: integer
          format: int32
      - name: userInfo
        in: path
        description: Informations that should be updated for the user
        required: true
        schema:
          type: object
      responses:
        "200":
          description: OK
    delete:
      description: Delete a user by id
      parameters:
      - name: id
        in: path
        description: ID of user
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /restaurant/{idRestaurant}:
    get:
      description: Get restaurant by id
      parameters:
      - name: idRestaurant
        in: path
        description: ID of the restaurant
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
    put:
      description: Update a restaurant by id
      parameters:
      - name: idRestaurant
        in: path
        description: ID of the restaurant
        required: true
        schema:
          type: integer
          format: int32
      - name: restaurantInfo
        in: path
        description: Informations that should be updated for the restaurant
        required: true
        schema:
          type: object
      responses:
        "200":
          description: OK
    delete:
      description: Delete a restaurant by id
      parameters:
      - name: idRestaurant
        in: path
        description: ID of the restaurant
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
  /restaurant/{idRestaurant}/trucks:
    get:
      description: Get all trucks from a restaurant
      parameters:
      - name: idRestaurant
        in: path
        description: ID of the restaurant
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK