name: CI/CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compile documentation
        run: |
        sudo apt install graphviz
          yarn install
          yarn build
      - name: deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: upload/sa/model