name: CI/CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: borales/actions-yarn@v1.22.18
        with:
          cmd: install
      - uses: borales/actions-yarn@v1.22.18
        with:
          cmd: build